import { getInv } from '../helpers/index.js';

export const ACHIEVEMENTS = [
  // --- Early Game ---
  { id: 'first_tire', title: 'Tire Curious', desc: 'Buy your first tire', icon: '🛞', coins: 2,
    check: g => getInv(g) >= 1,
    progress: g => ({ current: Math.min(getInv(g), 1), target: 1 }) },
  { id: 'first_sale', title: 'First Sale', desc: 'Sell your first tire', icon: '💵', coins: 5,
    check: g => g.totalSold >= 1,
    progress: g => ({ current: Math.min(g.totalSold || 0, 1), target: 1 }) },
  { id: '10_sales', title: 'Getting Rolling', desc: 'Sell 10 tires', icon: '🔟', coins: 10,
    check: g => g.totalSold >= 10,
    progress: g => ({ current: Math.min(g.totalSold || 0, 10), target: 10 }) },
  { id: '100_sales', title: 'Centurion', desc: 'Sell 100 tires', icon: '💯', coins: 50,
    check: g => g.totalSold >= 100,
    progress: g => ({ current: Math.min(g.totalSold || 0, 100), target: 100 }) },
  { id: '1000_sales', title: 'Tire Tycoon', desc: 'Sell 1,000 tires', icon: '🏆', coins: 250,
    check: g => g.totalSold >= 1000,
    progress: g => ({ current: Math.min(g.totalSold || 0, 1000), target: 1000 }) },

  // --- Revenue ---
  { id: 'rev_1k', title: 'First Grand', desc: 'Earn $1,000 in total revenue', icon: '💰', coins: 10,
    check: g => g.totalRev >= 1000,
    progress: g => ({ current: Math.min(g.totalRev || 0, 1000), target: 1000 }) },
  { id: 'rev_10k', title: 'Five Figures', desc: 'Earn $10,000 in total revenue', icon: '💰', coins: 25,
    check: g => g.totalRev >= 10000,
    progress: g => ({ current: Math.min(g.totalRev || 0, 10000), target: 10000 }) },
  { id: 'rev_100k', title: 'Six Figures', desc: 'Earn $100,000 in total revenue', icon: '💎', coins: 75,
    check: g => g.totalRev >= 100000,
    progress: g => ({ current: Math.min(g.totalRev || 0, 100000), target: 100000 }) },
  { id: 'rev_1m', title: 'Millionaire', desc: 'Earn $1,000,000 in total revenue', icon: '👑', coins: 500,
    check: g => g.totalRev >= 1000000,
    progress: g => ({ current: Math.min(g.totalRev || 0, 1000000), target: 1000000 }) },

  // --- Business ---
  { id: 'first_shop', title: 'Grand Opening', desc: 'Open your first shop', icon: '🏪', coins: 10,
    check: g => (g.locations || []).length >= 1,
    progress: g => ({ current: Math.min((g.locations || []).length, 1), target: 1 }) },
  { id: '2_shops', title: 'Expanding', desc: 'Own 2 shops', icon: '🏬', coins: 25,
    check: g => (g.locations || []).length >= 2,
    progress: g => ({ current: Math.min((g.locations || []).length, 2), target: 2 }) },
  { id: '5_shops', title: 'Chain Reaction', desc: 'Own 5 shops', icon: '🏙️', coins: 100,
    check: g => (g.locations || []).length >= 5,
    progress: g => ({ current: Math.min((g.locations || []).length, 5), target: 5 }) },
  { id: 'first_hire', title: 'Boss Mode', desc: 'Hire your first employee', icon: '🧑‍🔧', coins: 10,
    check: g => { const s = g.staff || {}; return (s.techs||0) + (s.sales||0) + (s.managers||0) + (s.drivers||0) >= 1; },
    progress: g => { const s = g.staff || {}; const t = (s.techs||0) + (s.sales||0) + (s.managers||0) + (s.drivers||0); return { current: Math.min(t, 1), target: 1 }; } },
  { id: 'first_supplier', title: 'Supply Line', desc: 'Establish a supplier relationship', icon: '🤝', coins: 5,
    check: g => (g.unlockedSuppliers || []).length >= 1,
    progress: g => ({ current: Math.min((g.unlockedSuppliers || []).length, 1), target: 1 }) },
  { id: 'warehouse', title: 'Warehouse Unlocked', desc: 'Purchase a warehouse', icon: '🏭', coins: 30,
    check: g => !!g.hasWarehouse,
    progress: g => ({ current: g.hasWarehouse ? 1 : 0, target: 1 }) },

  // --- Reputation ---
  { id: 'rep_10', title: 'Known Name', desc: 'Reach 10 reputation', icon: '⭐', coins: 10,
    check: g => g.reputation >= 10,
    progress: g => ({ current: Math.min(g.reputation || 0, 10), target: 10 }) },
  { id: 'rep_25', title: 'Respected', desc: 'Reach 25 reputation', icon: '🌟', coins: 30,
    check: g => g.reputation >= 25,
    progress: g => ({ current: Math.min(g.reputation || 0, 25), target: 25 }) },
  { id: 'rep_50', title: 'Legendary', desc: 'Reach 50 reputation', icon: '✨', coins: 150,
    check: g => g.reputation >= 50,
    progress: g => ({ current: Math.min(g.reputation || 0, 50), target: 50 }) },

  // --- Channels ---
  { id: 'ecom', title: 'Digital Storefront', desc: 'Launch your e-commerce channel', icon: '🛒', coins: 25,
    check: g => !!g.hasEcom,
    progress: g => ({ current: g.hasEcom ? 1 : 0, target: 1 }) },
  { id: 'wholesale', title: 'Bulk Dealer', desc: 'Start selling wholesale', icon: '📦', coins: 25,
    check: g => !!g.hasWholesale,
    progress: g => ({ current: g.hasWholesale ? 1 : 0, target: 1 }) },

  // --- Van Warrior / Flea / Car Meet ---
  { id: 'road_warrior', title: 'Road Warrior', desc: 'Sell 100 tires from your van (no shops)', icon: '🚐', coins: 50,
    check: g => (g.vanTotalSold || 0) >= 100,
    progress: g => ({ current: Math.min(g.vanTotalSold || 0, 100), target: 100 }) },
  { id: 'van_life', title: 'Van Life', desc: 'Profitable for 30 days with only a van', icon: '🏕️', coins: 100,
    check: g => (g.vanOnlyDays || 0) >= 30,
    progress: g => ({ current: Math.min(g.vanOnlyDays || 0, 30), target: 30 }) },
  { id: 'flea_king', title: 'Flea Market King', desc: 'Sell 200 tires at flea market stands', icon: '🏪', coins: 75,
    check: g => (g.fleaMarketTotalSold || 0) >= 200,
    progress: g => ({ current: Math.min(g.fleaMarketTotalSold || 0, 200), target: 200 }) },
  { id: 'car_meet_legend', title: 'Car Meet Legend', desc: 'Attend 10 car meets', icon: '🏎️', coins: 100,
    check: g => (g.carMeetsAttended || 0) >= 10,
    progress: g => ({ current: Math.min(g.carMeetsAttended || 0, 10), target: 10 }) },
  { id: 'summer_hustler', title: 'Summer Hustler', desc: 'Sell 50 tires at car meets', icon: '☀️', coins: 150,
    check: g => (g.carMeetTotalSold || 0) >= 50,
    progress: g => ({ current: Math.min(g.carMeetTotalSold || 0, 50), target: 50 }) },
];
