export const MANUFACTURERS = [
  { id: "shandong", n: "Huadong Rubber Group", ic: "\u{1F1E8}\u{1F1F3}", region: "China", tires: ["allSeason", "lightTruck", "commercial"], disc: .28, freight: 4500, containerQty: 500, leadWeeks: 8, partnerCost: 50000, quality: .85, desc: "Cheapest per tire. 8-week ocean freight. Huge containers." },
  { id: "thai_union", n: "SiamTrak Industries", ic: "\u{1F1F9}\u{1F1ED}", region: "Thailand", tires: ["allSeason", "performance", "lightTruck"], disc: .24, freight: 3800, containerQty: 400, leadWeeks: 7, partnerCost: 40000, quality: .9, desc: "Solid quality. 7-week lead. Good performance line." },
  { id: "apex_domestic", n: "Patriot Tire USA", ic: "\u{1F1FA}\u{1F1F8}", region: "Domestic", tires: ["allSeason", "performance", "winter", "lightTruck"], disc: .14, freight: 1200, containerQty: 200, leadWeeks: 2, partnerCost: 80000, quality: .95, desc: "2-week domestic freight. Premium quality. Higher cost." },
  { id: "euro_premium", n: "Rheingold Reifen AG", ic: "\u{1F1E9}\u{1F1EA}", region: "Germany", tires: ["performance", "winter", "allSeason"], disc: .18, freight: 3200, containerQty: 300, leadWeeks: 5, partnerCost: 120000, quality: 1.0, desc: "Top-tier European brand. 5-week freight. Strong winter line." },
  { id: "hansung", n: "HanWoo Tire Co.", ic: "\u{1F1F0}\u{1F1F7}", region: "South Korea", tires: ["allSeason", "performance", "lightTruck", "commercial"], disc: .22, freight: 3500, containerQty: 350, leadWeeks: 6, partnerCost: 60000, quality: .92, desc: "Great value. Wide selection. 6-week ocean freight." },
  { id: "ironwheel_ag", n: "IronTrak Industries", ic: "\u{1F69C}", region: "Domestic", tires: ["tractor", "implement", "atv"], disc: .16, freight: 2200, containerQty: 80, leadWeeks: 3, partnerCost: 90000, quality: .95, desc: "THE ag tire manufacturer. 3-week domestic. Smaller loads." },
  { id: "bharat_ag", n: "Bharat Krishi Rubber", ic: "\u{1F1EE}\u{1F1F3}", region: "India", tires: ["tractor", "implement", "atv"], disc: .3, freight: 4000, containerQty: 120, leadWeeks: 9, partnerCost: 45000, quality: .82, desc: "Cheapest ag tires on earth. 9-week freight. Volume play." },
];
