export const MONET = {
  adRevPerView: .003,
  premiumMonthly: 4.99,
  premiumYearly: 29.99,
  adContent: [
    { brand: "TireZone", text: "\u{1F525} TireZone SALE \u2014 All-Season Starting $79!", color: "#e94560" },
    { brand: "AutoParts+", text: "\u26A1 AutoParts+ \u2014 Free Shipping on Orders $99+", color: "#4488cc" },
    { brand: "QuickLube Pro", text: "\u{1F6E2}\uFE0F QuickLube Pro \u2014 Oil Change $29.99", color: "#00d4aa" },
    { brand: "InsureMyRide", text: "\u{1F6E1}\uFE0F InsureMyRide \u2014 Save 15% on Auto Insurance", color: "#7b61ff" },
    { brand: "FleetMaster", text: "\u{1F69B} FleetMaster GPS \u2014 Track Every Truck", color: "#f0c040" },
    { brand: "TireTech Academy", text: "\u{1F4DA} TireTech Academy \u2014 Certify Your Techs", color: "#cc7733" },
  ],
  coinRewards: {
    weekSurvived: 5,
    shopOpened: 50,
    firstWarehouse: 100,
    acquisitionComplete: 75,
    revenueTarget100K: 200,
    revenueTarget1M: 500,
    wholesaleClientSigned: 25,
    tpoContractSigned: 40,
    ecomLaunched: 150,
    distributorUnlocked: 300,
    marketplaceLaunched: 30,
    liquidationBought: 20,
    liquidationSold: 35,
    installerRecruited: 25,
    becameInstaller: 40,
  },
  cosmetics: [
    { id: "gold_name", n: "Gold Name Badge", cost: 200, desc: "Your name in gold on leaderboard" },
    { id: "custom_logo", n: "Custom Shop Logo", cost: 100, desc: "Upload your own logo" },
    { id: "premium_truck", n: "Premium Delivery Truck", cost: 150, desc: "Custom truck skin" },
    { id: "neon_sign", n: "Neon Shop Sign", cost: 75, desc: "Animated sign on your shops" },
    { id: "fireworks", n: "Fireworks Celebration", cost: 50, desc: "Fireworks on achievements" },
    { id: "map_trail", n: "Map Trail Effect", cost: 120, desc: "Trail on the map showing your empire" },
  ],
};
